### ISSUE TITLE
Create Projects page

### ISSUE THREAD

**Issue by tomsansome** [coders-for-corbyn/coders-for-corbyn.github.io#2]
Could this be linked directly to Github and list all of our repos on here maybe? Discuss.

**Comment by Kriskit** [comment]
Could use the Github API - It's got CORS enabled, so could use javascript to get a list of all the repos:

https://api.github.com/orgs/coders-for-corbyn/repos

**Comment by tomsansome** [comment]
Ooo that is lovely @Kriskit, +1 from me!
