### ISSUE TITLE
Discord widget takes up too much space on mobile

### ISSUE THREAD

**Issue by TomFromThePool** [coders-for-corbyn/coders-for-corbyn.github.io#30]
The Discord widget on mobile takes up over half the screen - let's just hide it completely and restore it only for tablets and larger screens.

**Comment by jonathanlloyd** [comment]
@TomFromThePool is this fixed? Looks good on my phone/responsive mode in my browser

**Comment by TomFromThePool** [comment]
@jonathanlloyd Yep looks good - my bad! It's been a long day! Closing :)
